application: coding-craft
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /js
  static_dir: js
- url: /images
  static_dir: images
- url: /textures
  static_dir: js_src/node_modules/painterly-textures/textures
- url: /.*
  script: main.application


libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
